### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files - in app/config/security.yml, line 13

### ISSUE THREAD

**Issue by yalit** [yalit/jmjbe#3]
**[in app/config/security.yml, line 13](https://github.com/yalit/jmjbe/blob/47b244dd2442d700e403a05895c95c93854038c7/app/config/security.yml#L13)**

> A sensitive data has been detected in your configuration file (`password` parameter). You should consider storing it in a single parameter file.

```

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
                    nannick: { password: 17qxLTNK, roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:   ^/
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/ba157280-12d8-4d7c-83f6-15b9259e460d/analyses/1)_
